# Generated by Django 5.2.4 on 2025-10-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_post_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='clerk_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
