# Generated by Django 5.2.4 on 2025-11-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_clerk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'Utilisateur')], default='user', max_length=20),
        ),
    ]
