# Generated by Django 5.2.4 on 2025-11-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='clerk_id',
            field=models.CharField(blank=True, help_text="ID unique correspondant à l'utilisateur dans Clerk", max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'Utilisateur')], default='user', help_text="Rôle de l'utilisateur pour le dashboard", max_length=20),
        ),
    ]
