# Generated by Django 5.2.4 on 2025-11-11 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_post_engagement_post_platform_alter_post_status_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
