# Generated by Django 5.2.4 on 2025-11-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_post_options_alter_post_status_linkedinprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedinprofile',
            name='linkedin_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
