# Generated by Django 5.2.4 on 2025-11-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_post_options_remove_subscription_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Utilisateur'), ('premium', 'Premium'), ('admin', 'Administrateur')], default='user', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Gratuit'), ('premium', 'Premium'), ('enterprise', 'Entreprise')], default='free', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('cancelled', 'Annulé')], default='inactive', max_length=20),
        ),
    ]
